### ISSUE TITLE
[Feature] - Relying Party Request URI response

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#10]
- [x] In the flow Same Device return an URL
- [x] In the flow cross Device return a QRCode

**Comment by Pyscho79** [comment]
Example of deeplink: "eudiw://authorize?client_id=https://verifier.example.org&request_uri=https://verifier.example.org/request_uri"

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-python/commit/941a42524dbb20d144545a0f1b87a7884db43c88
