### ISSUE TITLE
pre auth endpoint must check the session state and the previous authn session

### ISSUE THREAD

**Issue by peppelinux** [italia/eudi-wallet-it-python#109]
we need to filter out the requests that lands on the disco page without having processed through a SAML2/OIDC frontend

this is required for both UX and security

**Comment by Zicchio** [comment]
Asking as confirmation.

Is this issue associated to this in-code warning?
https://github.com/italia/eudi-wallet-it-python/blob/ac69db481a88842556dc58e849fb6331df2c020f/pyeudiw/satosa/default/openid4vp_backend.py#L179-L182
