### ISSUE TITLE
Change the text "QR Code" to "codice QR"

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#116]
It is suggested to put the text "codice QR" everywhere in the flow/interface (titles, subtitles, etc..) instead of "QR Code" to make the language simpler and more consistent with the IT Wallet interface on the IO app.

--> This is a NEW requirement

**Comment by peppelinux** [comment]
non lo so, parliamone.

Non so se sia più compresibile qrCode o codice QR, se usassimo una icona affianco QrCode?

**Comment by RosaliaGaleano** [comment]
Soltanto un bel test di usabilità potrebbe darci questa risposta purtroppo.. Nel frattempo suggerirei un flusso su desktop consistente e coerente con quanto progettato su app IO anche dal punto di vista dei termini utilizzati.

**Comment by peppelinux** [comment]
Done
