### ISSUE TITLE
Modify the subtitle inside the modal “Autenticazione annullata”

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#119]
It is suggested that the previous text be changed with the one here: " Per accedere al servizio prova ad autenticarti nuovamente prestando il consenso alla presentazione dei tuoi dati dall'app IO."

--> This is a NEW requirement

**Comment by peppelinux** [comment]
Done 6a16eb2c4f058e5a9f67f259365482248461d636
