### ISSUE TITLE
[Feature] - Relying Party Entity Configuration

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#12]
According to the [Trust Model](https://italia.github.io/eidas-it-wallet-docs/en/trust.html) section, the Verifier is a Federation Entity and MUST expose a .well-known endpoint containing its Entity Configuration.

Refer to entity_configuration method and [backend configuration](https://github.com/italia/eudi-wallet-it-python/blob/cb5e26430cc21088683f525cfda230d7289c59c4/example/eudi_wallet_python_backend.yml).

Below a non-normative example of the request made by the Wallet Instance to the openid-federation .well-known endpoint to obtain the Relying Party Entity Configuration:

- [X] Add metadata to configuration 
- [x] Method Yaml to Json
- [x] Return json metadata
- [ ] #47

**Comment by Pyscho79** [comment]
@peppelinux  the issue is complete but we have a dubt regarding to create a file readme for documents methods, suggest to use a swagger file for this scope. 
confirm It?

**Comment by peppelinux** [comment]
the endpoints are documented in the technical specs

before doing a swagger (similarly made in projects like [this](https://github.com/italia/spid-cie-oidc-django#openapi-schema-3)) we need a short, clear and concrete documentation that explain how to setup, configure and execute this project

the api will be refactored and probably change before deciding to have a oas3 specs, that should come after the release 0.6.0
