### ISSUE TITLE
Remove the text “Non hai ricevuto la notifica?” from the modal “Continua sul tuo smartphone”

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#120]
Remove the text “Non hai ricevuto la notifica? Puoi trovarla direttamente all'interno dell'app IO. Se hai più dispositivi mobili con l'app IO, scegli su quale dispositivo preferisci ricevere le notifiche” as there is no wallet engagement notification in the flow.

--> This is a NEW requirement

**Comment by peppelinux** [comment]
Done 318cadb67f995a2ea4ef6ae6937edbe9f1ad1080
