### ISSUE TITLE
Align the modal subtitle to the left

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#122]
Align the subtitle of the modals "Inquadra codice QR", "Continua sul tuo smartphone", "Autenticazione annullata" and "Autenticazione fallita" to the left. (check the prototype)

**Comment by peppelinux** [comment]
please provide the link to the prototype here :pray:

**Comment by RosaliaGaleano** [comment]
hi @peppelinux, find here the prototype link:
https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=4817-7230&mode=design&t=uwgMmLr6dLKw0l3w-4

**Comment by peppelinux** [comment]
@RosaliaGaleano as requested during the last meeting, the modal/frame will be replace by a specialized page with the QR Code

**Comment by RosaliaGaleano** [comment]
@peppelinux I'm going to modify the prototype. I'll send you the update link

**Comment by RosaliaGaleano** [comment]
@peppelinux here the updated prototype https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5070-5950&mode=design&t=QcrNXIfM2EKEU30V-4

As you can see, the flow happens within a page and the final "positive feedback" was restored.

**Comment by peppelinux** [comment]
according to figma the subtitle are all centered

@RosaliaGaleano please feel free to re-open this issue if required
