### ISSUE TITLE
Review font size

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#123]
The size of the title and text in the modals does not appear consistent with the prototype. The proportion should be: title 24px and body text 18px. (check the prototype)

**Comment by peppelinux** [comment]
aligned here 488da60f7ccfc986079420a0a5596d088714121d

@RosaliaGaleano what about the Button text size? I've found 20px, is it good for you?

**Comment by peppelinux** [comment]
Ok

![immagine](https://github.com/italia/eudi-wallet-it-python/assets/1297620/80cdd378-d687-4f5f-876d-1b912ed5ac57)
