### ISSUE TITLE
Add "Chiudi" button

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#126]
Add “Chiudi” secondary button within the “Inquadra il codice QR”, "Continua sul tuo smartphone", "Autenticazione annullata" and "Autenticazione fallita" modals. (check the prototype)

**Comment by peppelinux** [comment]
@RosaliaGaleano is this still valid or removed in the figma?

**Comment by RosaliaGaleano** [comment]
@peppelinux it's outdated because we turned the modal into a page.
