### ISSUE TITLE
add eudi wallet it to ita-button set

### ISSUE THREAD

**Issue by MdreW** [italia/eudi-wallet-it-python#131]
Hi All,
I would like add the the **EUDI Wallet IT** button to [ita-button](https://github.com/isprambiente/ita-button) project. 
Ita button is a style collection for italian auth buttons. Like [spid-sp-access-button](https://github.com/italia/spid-sp-access-button) but without external requirements (bootstrap, jquery, ecc...)
I can use the [wallet_icon.svg](https://github.com/italia/eudi-wallet-it-python/blob/dev/example/satosa/static/wallet-it/wallet_icon.svg) image?

**Comment by peppelinux** [comment]
yes you can @MdreW !

**Comment by MdreW** [comment]
Thank you
