### ISSUE TITLE
`./satosa/backend.py:659`:            # TODO: validate wia scheme using pydantic

### ISSUE THREAD

**Issue by salvatorelaiso** [italia/eudi-wallet-it-python#141]

**Comment by salvatorelaiso** [comment]
Nella WIA, quale dei due identificatori è corretto per il campo `attested_security_context`?

In questi due test, vengono utilizzate due chiavi diverse:

https://github.com/italia/eudi-wallet-it-python/blob/9a32ad139ea1cd05aac2d9aee737896b8a4a04a1/pyeudiw/tests/oauth2/test_dpop.py#L23

https://github.com/italia/eudi-wallet-it-python/blob/9a32ad139ea1cd05aac2d9aee737896b8a4a04a1/pyeudiw/tests/openid4vp/schemas/test_wallet_instance_attestation.py#L26


La [documentazione](https://italia.github.io/eudi-wallet-it-docs/versione-corrente/en/wallet-instance-attestation.html) riporta la dicitura estesa, ci atteniamo a questa, @peppelinux?

**Comment by salvatorelaiso** [comment]
Preciso che lo schema Pydantic attuale prevede la dicitura estesa.

https://github.com/italia/eudi-wallet-it-python/blob/9a32ad139ea1cd05aac2d9aee737896b8a4a04a1/pyeudiw/openid4vp/schemas/wallet_instance_attestation.py#L49

**Comment by peppelinux** [comment]
attualmente è attested_security_context ma stiamo migrando a `aal` qui
https://github.com/italia/eudi-wallet-it-docs/pull/155

dato che con lo sviluppo siamo in una milestone avanzata che guarda alla prossima milestone della documentazione, ti chiedo di allineare `aal`
