### ISSUE TITLE
Delete CTA "Ho bisogno di più tempo"

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#147]
As agreed, delete the CTA “Ho bisogno di più tempo”.

**[View the prototype v3](https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5192-6575&mode=design&t=FP7J48TNeR77W9rV-4)**

**Comment by davidelongo-ey** [comment]
Attività eseguita e finalizzata il 18/12/2023 (vedi PR: https://github.com/italia/Satosa-Saml2Spid/pull/98)
