### ISSUE TITLE
Review and update the subtitles

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#148]
Provide a dynamic field to describe the type of service requested by the user and the name of the Relying Party. When the service is not available, report only the name of the RP. Following are the subtitles of the impacted sections:
 
Page > “**[Inquadra il codice QR](https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5192-6575&mode=design&t=FP7J48TNeR77W9rV-4)**”.
Subtitle > “Usa la funzionalità “Inquadra” dell’app IO per accedere con IT Wallet al servizio [nome_servizio] di [nome_rp].
or > “Usa la funzionalità “Inquadra” dell’app IO per accedere con IT Wallet ai servizi di [nome_rp].”

Page > “**[Autenticazione completata!](https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5192-6701&mode=design&t=FP7J48TNeR77W9rV-4)**”
Subtitle > “Da questo momento puoi iniziare a utilizzare il servizio [nome_servizio] di [nome_rp].”
or > “Da questo momento puoi iniziare a utilizzare i servizi di [nome_rp].”

Page > “**[Autenticazione annullata](https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5192-8319&mode=design&t=FP7J48TNeR77W9rV-4)**”
Subtitle > “Premi “Riprova” per autenticarti nuovamente su [nome_rp]. Ricorda di acconsentire alla lettura dei tuoi dati sull’appIO.”

Page > “**[Autenticazione fallita](https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5193-9470&mode=design&t=FP7J48TNeR77W9rV-4)**”
Subtitle > “Qualcosa non ha funzionato. Premi “Riprova” per autenticarti nuovamente su [nome_rp] oppure segui le istruzioni visibili sull’app IO.”

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-python/pull/220
