### ISSUE TITLE
Update icons

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#150]
Replace the placeholder square with the icons shown inside the prototype. View details:

- Page “Continua sul tuo smartphone” insert mobile icon ([link](https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5192-6685&mode=design&t=FP7J48TNeR77W9rV-4));
- Page “Autenticazione completata!” insert check icon ([link](https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5192-6701&mode=design&t=FP7J48TNeR77W9rV-4));
- Page “Autenticazione annullata” and “Autenticazione fallita” insert cross icon ([link](https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=5192-8319&mode=design&t=FP7J48TNeR77W9rV-4)).

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-python/pull/220
