### ISSUE TITLE
`./satosa/backend.py:145`:        # TODO: move this to the trust evaluation helper

### ISSUE THREAD

**Issue by davidelongo-ey** [italia/eudi-wallet-it-python#155]

**Comment by salvatorelaiso** [comment]
This TODO was found in the file [pyeudiw/satosa/trust.py](https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/satosa/trust.py).

The same contains also the following TODO:
https://github.com/italia/eudi-wallet-it-python/blob/bfabbe02534aae6003629233f70ba9257fc839f6/pyeudiw/satosa/trust.py#L120-L120

**Comment by salvatorelaiso** [comment]
Closed by #189
