### ISSUE TITLE
`./jwk/schema.py:9`:    # TODO: verify if is optional

### ISSUE THREAD

**Issue by davidelongo-ey** [italia/eudi-wallet-it-python#170]

**Comment by salvatorelaiso** [comment]
This TODO refers to the following:

https://github.com/italia/eudi-wallet-it-python/blob/43454bf31d22f67b0c5ee6a66da69efe1c27f9f0/pyeudiw/jwk/schema.py#L9-L22


According to the [RFC 7517 section 4.4](https://datatracker.ietf.org/doc/html/rfc7517#section-4.4) it is indeed optional.
Can we close this issue by simply removing its TODO in a dedicated PR or do we prefer to enforce the use of `alg` nonetheless?

**Comment by peppelinux** [comment]
@salvatorelaiso got It

Please remove that todo by reporting in the PR the evidence taken from rfc7517 and then close this issue

Thx
