### ISSUE TITLE
Eliminare i loghi presenti al fondo dei bottoni

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#18]
Eliminare i loghi presenti al fondo dei bottoni (non hanno una vera utilità e rischiano di confondere l’utente aggiungendo complessità e aumentando lo sforzo cognitivo di lettura della pagina). Questa pagina è tecnicamente una landing page, quindi non dovrebbe come da best practice contenere altri elementi cliccabili che distraggano l’utente dalle azioni primarie, portandolo ad abbandonare il flusso di accesso.

**Comment by MurruAlessio** [comment]
loghi rimossi:

https://github.com/italia/eudi-wallet-it-python/pull/32
