### ISSUE TITLE
[Feature] - Integrazione plug-in SAML2 to wordpress

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#2]
- [x] Creation example project in repository:
    - [x] WordPress setup
    - [x] WordPress bootstrap Italia template setup
    - [x] WordPress SAML2 OneLogin plugin setup
    - [x] WordPress SAML2 OneLogin Donwload Metadata from wordpress sp
    - [x] WordPress SAML2 OneLogin Test with IDP spid-saml-check
 - [x] Setup Documentation: 
    - [x] WordPress setup
    - [x] WordPress bootstrap Italia template setup
    - [x] WordPress SAML2 OneLogin plugin setup
 - [ ] #41
    - [ ] readme docker image setup

**Comment by MurruAlessio** [comment]
Created WordPress instance using docker-compose

This [commit](https://github.com/italia/eudi-wallet-it-satosa-rp/commit/dc4b0c5078d341de5a47836ba4e0bfc629c28c4d) includes the docker-compose file used to create a WordPress instance with multiple containers, including a `database` container for the MariaDB database and a `phpmyadmin` container for managing the database through a web interface.

The WordPress container uses version 5.4 to ensure compatibility with the ItaliaWP2 theme. However, it should be noted that this version of WordPress has some vulnerabilities that are fixed in version 6.6.

**Comment by MurruAlessio** [comment]
I have successfully installed the ItaliaWP2 theme from the GitHub repository https://github.com/italia/design-wordpress-theme-italiaWP2 and set it as the active theme for WordPress instance.

**Comment by peppelinux** [comment]
Can you see/download the wordpress saml2 metadata?
you have to download the satosa frontend metadata to your sp before starting an authn request

**Comment by peppelinux** [comment]
> Created WordPress instance using docker-compose
> 
> The commit includes the docker-compose file used to create a WordPress instance with multiple containers, including a `database` container for the MariaDB database and a `phpmyadmin` container for managing the database through a web interface.
> 
> The WordPress container uses version 5.4 to ensure compatibility with the ItaliaWP2 theme. However, it should be noted that this version of WordPress has some vulnerabilities that are fixed in version 6.6.

since it is just for the example project, we just have to indicate in the tutorial/configuration/readme that this is just for demo purpose and MUST NOT used in production contexts

we use this WP just as an example of legacy infrastructure

**Comment by Pyscho79** [comment]
> Can you see/download the wordpress saml2 metadata? you have to download the satosa frontend metadata to your sp before starting an authn request

Yew confirm download metadata form wordpress

**Comment by Pyscho79** [comment]
@MurruAlessio need to test the new release **Satosa-Saml2Spid v1.0.1** 
https://github.com/italia/Satosa-Saml2Spid/releases/tag/v1.0.1

**Comment by MurruAlessio** [comment]
below is the pull request with SaToSa integration changes for Wordpress plugin integration test
https://github.com/italia/Satosa-Saml2Spid/pull/77
