### ISSUE TITLE
Impostare una gerarchia delle informazioni, dell’interazione e affordance delle CTA

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#20]
Impostare una gerarchia delle informazioni, dell’interazione e affordance delle CTA: occorre chiarire la gerarchia delle informazioni principali e quella delle azioni che si vuole l’utente compia mediante la schermata. Se l’obiettivo è promuovere “IT wallet” è corretto che questo sia valorizzato come CTA primary e che gli altri metodi di autenticazione siano secondari. Un discorso a parte (tertiary) meriterebbero poi le eventuali altre identità federate non “di stato” (es. IDEM).

**Comment by Pyscho79** [comment]
@RosaliaGaleano non è chiara che tipo di action ci aspettiamo dai Dev.

**Comment by RosaliaGaleano** [comment]
@Pyscho79 con questa issue si vuole proporre una soluzione per rendere più leggibile la schermata d'accesso: e cioè quella di utilizzare i pulsanti di primo livello per identificare lo strumento di identificazione su cui si vuole strategicamente spingere (es IT wallet) e impostare come secondari tutti gli altri.
