### ISSUE TITLE
Backend Code linting

### ISSUE THREAD

**Issue by peppelinux** [italia/eudi-wallet-it-python#219]
Running flake8 on the soruce tree shown several code style issues

````
  flake8 pyeudiw --count --select=E9,F63,F7,F82 --show-source --statistics
  flake8 pyeudiw --count --exit-zero --statistics  --max-line-length 160
````
for example: https://github.com/italia/eudi-wallet-it-python/actions/runs/7473221007/job/20336981885?pr=218#step:8:12

please cleanup and resolve all thos issue in a way that flake8 would return 0 issues

**Comment by davidelongo-ey** [comment]
resolved via PR https://github.com/italia/eudi-wallet-it-python/pull/224
