### ISSUE TITLE
Sostituire l’icona “cellulare” nel bottone di accesso con IT Wallet

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#22]
Sostituire l’icona “cellulare” nel bottone di accesso con IT Wallet in quanto anche altri sistemi di autenticazione prevedono l’interazione con un app. In attesa di un vero e proprio studio di branding del Wallet, scegliere una icona più consona come, ad esempio, quella attualmente selezionata per identificare visivamente in app IO il Wallet stesso (per maggiori dettagli, vedi proposta DTD).

**Comment by MurruAlessio** [comment]
Icona wallet-it modificata con icona demo da wallet:

https://github.com/italia/eudi-wallet-it-python/pull/32
