### ISSUE TITLE
Unused parameters in `qrcode`

### ISSUE THREAD

**Issue by salvatorelaiso** [italia/eudi-wallet-it-python#226]
The following parameters, under `config.qrcode` in [example/satosa/pyeudiw_backend.yaml](https://github.com/italia/eudi-wallet-it-python/blob/d2ab68d207345920d0816aaf733a38ffd51326e8/example/satosa/pyeudiw_backend.yaml), are not used anymore:
- size
- logo_path
- use_zlib

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-python/pull/230
