### ISSUE TITLE
Prevedere un disclaimer "alert non normativo"

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#23]
Prevedere un disclaimer per indicare che quanto presente non è definito a livello normativo. 

- [x] Mockup with placeholder
- [x] Disclaimer Text proposal to approver by Designer

**Comment by MurruAlessio** [comment]
Disclaimer aggiunto:


https://github.com/italia/eudi-wallet-it-python/pull/32
