### ISSUE TITLE
Proposta grafica non normativa

### ISSUE THREAD

**Issue by RosaliaGaleano** [italia/eudi-wallet-it-python#24]
Prendere esempio dalla illustrazione allegata per la UX/UI della pagina e i testi.
![Desktop - 10 (1)](https://github.com/italia/eudi-wallet-it-python/assets/139998796/820190ed-7482-4d2a-8496-1225ae6de746)

**Comment by RosaliaGaleano** [comment]
@Pyscho79 condivido il link di dettaglio della proposta grafica https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=4705%3A302709&mode=design&t=8jX1z6d8W8pcGvD8-1

**Comment by MurruAlessio** [comment]
Nuovo layout aggiunto con la seguente pull request: 
- https://github.com/italia/eudi-wallet-it-python/pull/32

**Comment by Pyscho79** [comment]
@RosaliaGaleano @peppelinux   Abbiamo sottomesso la PR per la pagina di Discovery ti segnalo che:

- il testo di disclaimer è stato inserito come warning box nella parte superiore tra la descrizione e gli action button 
- abbiamo allineato il testo del bottone IT Wallet alla dicitura 
- Abbiamo allegerito il testo di descrizione dei servizi SPID e CIE 

se la review della discovery page è okci servirebbe il figma della pagina di fruizione del QRCode
