### ISSUE TITLE
[Bug][Satosa] Default request and response routing logic is flipped

### ISSUE THREAD

**Issue by Zicchio** [italia/eudi-wallet-it-python#246]
According to the interface specification, the **Request**Handler **interface** https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/satosa/interfaces/request_handler.py defines the creation of the Request Object
https://github.com/italia/eudi-wallet-it-python/blob/52fcbece3fa77fefbd5e91181ac3e2e73fc5f098/pyeudiw/satosa/interfaces/request_handler.py#L16

But the default realization delegates this behaviour to the **Response**Handler default implementation https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/satosa/default/response_handler.py

Likewise, the interface ResponseHandler interface https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/satosa/interfaces/request_handler.py should process the `/authorize` response https://github.com/italia/eudi-wallet-it-python/blob/52fcbece3fa77fefbd5e91181ac3e2e73fc5f098/pyeudiw/satosa/interfaces/response_handler.py#L15 but this behaviour is actually delegated to the **Request**Handler default realization https://github.com/italia/eudi-wallet-it-python/blob/dev/pyeudiw/satosa/default/request_handler.py

Confronting the python docstring with the eudi it wallet specification suggest that the interface definition and docstring are correct, and the implementations are erroneously flipped.

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-python/pull/253
