### ISSUE TITLE
[Satosa] [Bug] Errore verifica corretteza in integration test

### ISSUE THREAD

**Issue by Zicchio** [italia/eudi-wallet-it-python#269]
L'esito finale dell'integration test controlla gli attributi ottenuti confrontandoli con quelli attesi in questa riga di codice

https://github.com/italia/eudi-wallet-it-python/blob/1cad07f7bb3ae8d6958d3b1cb3b65bea168ff866/example/satosa/integration_test/main.py#L270-L275

questo check non è formalmente corretto. Ad esempio, se l'autenticazione non genera nessun attributo dell'utente, o li genera con nome sbagliato, il test viene comunque superato.

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-python/pull/273
