### ISSUE TITLE
[Feature] - Creazione endpoint blank SaToSa

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#3]
- [x] #13
- [x] Development toolchain 
- [x] Repository Creation
- [ ] Discovery page with IT wallet authentication 
    - [x] Add Button Wallet IT with a smartphone icon
    - [x] Add ID entity ID in routing with identifier name "it-wallet"
    - [x] Validation URL for it-wallet
    - [ ] Check new docker image 
    - [ ] #43
- [x] Dummy SaToSa
    - [x] Creation backend .py 
    - [x] definition of utility service - class and methods 
    - [x] definition of endpoints with mockup response
    - [ ] #42

**Comment by Pyscho79** [comment]
Discovery page - button name "Wallet IT" add smartphone white icon from bootstrap template

**Comment by peppelinux** [comment]
> Discovery page - button name "Wallet IT" add smartphone white icon from bootstrap template

please add in CI a html linter on that static html page
