### ISSUE TITLE
Retention rule Session Storage

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#33]
Create to configure retention rule session

- [x] Create Doc
- [x] Create Configuration param (default: 2 years)
- [x] Add parameter in the configuration (storage.init_params.conf.data_ttl: in seconds)
- [x] Integrate TTL rule index in the constructor

Following this documentation: https://www.mongodb.com/docs/manual/tutorial/expire-data/

**Comment by peppelinux** [comment]
Done https://github.com/italia/eudi-wallet-it-python/pull/218
