### ISSUE TITLE
[DEMO] Docker Compose 

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#41]
- [x] MariaDb
- [x] Wordpress
- [x] MongoDb
- [x] Satosa SAMLtoSPID (Update repo relativo) Separate Docker Compose
- [x] Test Locale

**Comment by davidelongo-ey** [comment]
move to Satosa-Saml2Spid project 

[Saml2Spid](https://github.com/italia/Satosa-Saml2Spid/issues/92)
