### ISSUE TITLE
Add CI for html validator

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#43]
check linter integration with CI

**Comment by Pyscho79** [comment]
Regarding this task 

Require more details for action CI that should be taken with respect to the linter output

**Comment by peppelinux** [comment]
if the html is broken the CI must fail
if the html is not broken but something raises warnings, the CI MUST continue returning 0

**Comment by peppelinux** [comment]
Resolved by https://github.com/italia/eudi-wallet-it-python/pull/86
