### ISSUE TITLE
[DEMO] Review UX pagina utente wordpress template devlopers italia

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#45]
![image](https://github.com/italia/eudi-wallet-it-python/assets/138689915/d706a94b-184f-4060-8b3a-d2835eb73cfe)

Ti diamo visione della pagina di atterraggio su wordpress relativa alla demo

**Comment by peppelinux** [comment]
@Pyscho79 may w have also a screenshot of the first page, before the authentication happens?

**Comment by RosaliaGaleano** [comment]
If this page should appear after authentication, I suggest simplifying it and not repeating the data that the user has just displayed in the app for consent. 
If it takes many seconds to load the content of the post-login page, we could also provide a timed thank you page on desktop (to be omitted if loading is very fast).

View the reference here: https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=4829-14963&mode=design&t=hj7npyQvpghH43HP-4
