### ISSUE TITLE
trust evaluation 

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#52]
- [x] Documentazione da studiare 
- [x] wallet provider using wallet instance attestation: validate trust chain 
- [x] obtain trust chain and include in sign request object available in request_uri
- [x] evaluate issuer trust chain regarding the issuing the credentials (within vp token respnose_uri)

**Comment by Pyscho79** [comment]
Issue Sospesa

**Comment by peppelinux** [comment]
@PascalDR the trust chain MUST be included in the signed request object JWS headers, actually it is not

**Comment by peppelinux** [comment]
> @PascalDR the trust chain MUST be included in the signed request object JWS headers, actually it is not

Done in release v0.5.0

**Comment by peppelinux** [comment]
v0.5.0 has resolved this issue
