### ISSUE TITLE
evaluate with UX designers if Jinja2 template

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#53]
more discussion is required

**Comment by RosaliaGaleano** [comment]
Hello @Pyscho79, I leave here the link to the prototype with the authentication flow to be implemented (or to be discussed for a future implementation phase):
https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=4705%3A302709&mode=design&t=hj7npyQvpghH43HP-1

p.s. consider text and icons as placeholder

**Comment by MurruAlessio** [comment]
Hi @RosaliaGaleano could you provide me with a svg version of the wallet icon?
it would be much easier to integrate it to the discovery page, alternatively if you only have the png version available I would ask you for a white version and a blue version with no background.
Unfortunately I don't have the necessary permissions to download the item from figma.

**Comment by RosaliaGaleano** [comment]
@MurruAlessio, yes sure! Find the svg icon attached. Let me know if you need other icons or assets.
![wallet](https://github.com/italia/eudi-wallet-it-python/assets/139998796/f7da74ff-dee1-4a3a-b02a-38fc4ad9eda9)

**Comment by MurruAlessio** [comment]
Hi Rosalia! just a note regarding figma, the session expiration value will not be a static number but will be decided on the backend side depending on the specification. so that value could be different.


![Image](https://github.com/italia/eudi-wallet-it-python/assets/138689926/7e276d2d-6600-4059-9220-1f3962ba4736)

**Comment by RosaliaGaleano** [comment]
Hi Alessio! Yes, you are right! The prototype just shows an illustrative number in bold (120 sec represents the expiration time for SPID) but it's a dynamic one as you said
