### ISSUE TITLE
QR Code Polling

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#68]
In a Cross Device Flow the user-agent uses the JS (with WS or polling) made available in the QRCode Page to check if the authentication is successfully. For doing that it has to request to a specific URL (and also be authenticated with a session cookie that binds the unique-session-identifier, to avoid adversary to be able to made hijacks).

https://github.com/italia/eudi-wallet-it-docs/pull/87#issue-1830163472

**Comment by MurruAlessio** [comment]
PR opened: https://github.com/italia/eudi-wallet-it-python/pull/78
