### ISSUE TITLE
QRCode page

### ISSUE THREAD

**Issue by peppelinux** [italia/eudi-wallet-it-python#72]
The IAM Proxy parse the authorization request and shows the discovery page to the user, where they can select the authentication methods (wallet, spid, cie ...)

The user selects "IT Wallet" and the OpenID4VP backed handles the authentication session, starting with a page where the QRCode is presented together with some indication about opening the wallet instance, select "QRCode", frame the qrcode and what will happen next.

**Comment by RosaliaGaleano** [comment]
I suggest taking this proposal as a reference: https://www.figma.com/file/wvXrFloFfHi6kd0176yqBK/Accesso-%2F-UI-kit-baset?type=design&node-id=4817-7230&mode=design&t=hj7npyQvpghH43HP-4

**Comment by Pyscho79** [comment]
https://github.com/italia/eudi-wallet-it-python/issues/53

Define timeout regarding RP rule
