### ISSUE TITLE
SAML2 service provider test procedure

### ISSUE THREAD

**Issue by Pyscho79** [italia/eudi-wallet-it-python#90]
Create environment for testing cookie structure and session id

- [x] SPConfig with metadata retrieve from storage
- [x] create auth request and validate request_endpoint
- [x] IDPhint add WALLET 
- [x] SatosaSAML2 binding http_redirect 
- [ ] create trustchain su satosa
- [ ] get credentials and validate

**Comment by peppelinux** [comment]
Resolved by 0.5.0
